# Generated by Django 5.2.1 on 2025-06-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmodel',
            name='model_path',
            field=models.FileField(blank=True, help_text='Unggah file model yang sudah terlatih (misal: .pkl, .h5, .pt).', null=True, upload_to='trained_models/', verbose_name='Lokasi File Model'),
        ),
    ]
