# Generated by Django 5.2.1 on 2025-06-03 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projek', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Proyek')),
                ('description', models.TextField(verbose_name='Deskripsi Proyek')),
                ('location', models.CharField(max_length=255, verbose_name='Lokasi')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_projects', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Proyek',
                'verbose_name_plural': 'Proyek',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProblemFraming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.TextField(help_text='Jelaskan masalah bisnis yang ingin diselesaikan.', verbose_name='Deskripsi Masalah (Problem Statement)')),
                ('target_goal', models.TextField(help_text='Apa yang ingin dicapai secara terukur dengan solusi cerdas?', verbose_name='Target / Tujuan (Goal)')),
                ('stock_initial_state', models.TextField(blank=True, help_text='Deskripsikan kondisi awal entitas yang relevan dengan masalah (misal: jumlah inventory saat ini).', null=True, verbose_name='Stock (Kondisi/Ketersediaan Awal)')),
                ('input_inflow_description', models.TextField(blank=True, help_text='Data/informasi apa yang masuk dan memengaruhi masalah? (misal: data transaksi, harga pasar, pesanan baru).', null=True, verbose_name='Input Inflow')),
                ('output_outflow_description', models.TextField(blank=True, help_text='Hasil atau efek apa yang diharapkan dari sistem cerdas? (misal: rekomendasi, prediksi penjualan, deteksi anomali).', null=True, verbose_name='Output Outflow')),
                ('key_features_data', models.TextField(help_text='Variabel atau atribut data apa yang penting untuk model sistem cerdas?', verbose_name='Fitur Kunci / Data yang Diperlukan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='framed_problems', to=settings.AUTH_USER_MODEL, verbose_name='Di-frame oleh')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='problem_framing', to='projek.project', verbose_name='Proyek Terkait')),
            ],
            options={
                'verbose_name': 'Problem Framing',
                'verbose_name_plural': 'Problem Framing',
                'ordering': ['-created_at'],
            },
        ),
    ]
