# Generated by Django 5.2.1 on 2025-06-03 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projek', '0002_project_problemframing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_problem', models.TextField(help_text='Jelaskan masalah atau konteks yang membutuhkan dataset ini.', verbose_name='Deskripsi Masalah (Kebutuhan Dataset)')),
                ('target_for_dataset', models.TextField(help_text='Untuk tujuan apa dataset ini akan digunakan?', verbose_name='Target / Tujuan (Penggunaan Dataset)')),
                ('type_data_needed', models.CharField(help_text='Contoh: Data Transaksi, Data Sensor, Data Pelanggan, dll.', max_length=100, verbose_name='Tipe Data yang Dibutuhkan')),
                ('data_processing_activity', models.TextField(help_text='Deskripsikan pemrosesan awal yang dibutuhkan (misal: filtering, aggregation, anonymization).', verbose_name='Aktivitas Pemrosesan Data yang Diinginkan')),
                ('num_features', models.IntegerField(blank=True, help_text='Estimasi kolom data yang dibutuhkan.', null=True, verbose_name='Estimasi Jumlah Fitur')),
                ('dataset_size', models.CharField(blank=True, help_text='Contoh: 100GB, 1 Juta Baris, dll.', max_length=100, null=True, verbose_name='Estimasi Ukuran Dataset')),
                ('file_format', models.CharField(choices=[('CSV', 'CSV'), ('JSON', 'JSON'), ('SQL', 'SQL Dump'), ('Excel', 'Excel (XLSX)'), ('Other', 'Lainnya')], max_length=50, verbose_name='Format File yang Diinginkan')),
                ('start_date_needed', models.DateField(verbose_name='Tanggal Mulai Dibutuhkan')),
                ('end_date_needed', models.DateField(blank=True, help_text='Tanggal batas akhir data yang dibutuhkan (jika historis).', null=True, verbose_name='Tanggal Selesai Dibutuhkan')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('InProgress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50, verbose_name='Status Permintaan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_requests', to='projek.project', verbose_name='Proyek Terkait')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_datasets', to=settings.AUTH_USER_MODEL, verbose_name='Diminta Oleh')),
            ],
            options={
                'verbose_name': 'Permintaan Dataset',
                'verbose_name_plural': 'Permintaan Dataset',
                'ordering': ['-created_at'],
            },
        ),
    ]
